### ISSUE TITLE
无法下一步

### ISSUE THREAD

**Issue by reov** [zzcabc/Docker_Buildx_PixivBiu#2]
日志显示
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
Traceback (most recent call last):
File "/tmp/_MEIEKIgbE/app/lib/core/biu.py", line 136, in __login
args = {"token": tokenFile["token"], }
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main.py", line 37, in <module>
File "altfe/bridge.py", line 32, in run
File "altfe/interface/root.py", line 56, in instantiate
File "/tmp/_MEIEKIgbE/app/lib/core/biu.py", line 35, in __init__
self.auto()
File "/tmp/_MEIEKIgbE/app/lib/core/biu.py", line 48, in auto
self.__login() # 登录
File "/tmp/_MEIEKIgbE/app/lib/core/biu.py", line 147, in __login
if input(self.lang("loginHelper.is_need_to_get_token")) != "y":
EOFError: EOF when reading a line
[7] Failed to execute script 'main' due to unhandled exception!

是否继续? (y / n):

但是控制台显示
Error response from daemon: Container d584c4febae22db6641e015f63bc9a77247ff8bf6cecb84e3586df6fc44eda30 is not running

系统：unraid

**Comment by zzcabc** [comment]
尝试使用电脑端获取cookie，然后复制usr下的.token.json，上传unraid，映射到容器内部

**Comment by reov** [comment]
Command:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='pixivbiu' --net='bridge' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="pixivbiu" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='/plugins/dynamix.docker.manager/images/question.png' -p '4002:4001/tcp' -v '/mnt/user/appdata/Pixiv/config.yml':'/Pixiv/config.yml':'rw' -v '/mnt/user/Download/Pixiv':'/Pixiv/downloads':'rw' -v '/mnt/user/appdata/Pixiv/usr/.token.json':'/Pixiv/usr/.token.json':'rw' 'zzcabc/pixivbiu'
8821afdd42c790f97441cf5d280f7866f7a3b707fe88bb0f6754a971bd08d570

已映射

**Comment by zzcabc** [comment]
这里token应该有误，我测试的时候都是使用客户端进行获取token然后将token.json映射的

**Comment by reov** [comment]
什么客户端，我是按照readme里面做的啊

**Comment by zzcabc** [comment]
可以去下载txperl   原始的可执行版本   https://github.com/txperl/PixivBiu/releases/tag/v2.2.0b

**Comment by zzcabc** [comment]
> 写的获取token无法使用

然后正常登录之后在将usr目录下的.token.json映射进去

**Comment by reov** [comment]
我试验了很多次，情况是一样的，txperl的也不行

**Comment by kuusei** [comment]
pixiv使用Oauth2验证, 这个code的有效期很短, 建议直接在token处填refresh_token

关于refresh_token获取可以看这个https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362

**Comment by zzcabc** [comment]
抱歉拖了这么久

在获取`.token.json`的时候，我使用了本机可执行程序，获取code，然后将`.token.json`上传至服务器，并且映射到docker内，可能存在code错误，然后继续本地获取code，直到成功

**Comment by reov** [comment]
那应该怎么操作

**Comment by zzcabc** [comment]
> 那应该怎么操作

在https://github.com/txperl/PixivBiu/releases下载可执行程序，然后启动，在程序中输入code，直到可以成功登录，然后将user文件夹下的.token.json文件上传到unraid，然后映射到docker中，启动镜像

**Comment by zzcabc** [comment]
可以了吗，我测试了多次，从最新版客户端导入token.json文件，都可以使用

**Comment by SA8620** [comment]
你好，我也是Unraid docker。我是用這個方式建立
docker run -d \
    --name pixivbiu \
    --user $(id -u):$(id -g) \
    -p 4001:80 \
    -e sys.debug=false \
    -e sys.apiRoute="direct" \
    -e sys.proxy="no" \
    -e sys.language="zh" \
    -e sys.theme="multiverse" \
	-e sys.autoOpen=true \
	-e sys.ignoreOutdated=false \
    -e biu.search.maxThreads=8 \
    -e biu.search.loadCacheFirst=true \
    -e biu.search.maxCacheSizeMiB=512 \
    -e biu.download.mode="dl-single" \
    -e biu.download.aria2Host="localhost:6800" \
    -e biu.download.aria2Secret="xiaodi" \
    -e biu.download.deterPaths=true \
    -e biu.download.maxDownloading=8 \
    -e biu.download.saveURI="{ROOTPATH}/downloads/{date_today}/" \
    -e biu.download.saveFileName="{title}_{work_id}" \
    -e biu.download.autoArchive=true \
    -e biu.download.whatsUgoira=webp \
    -e biu.download.imageHost="https://i.pximg.net" \
    -e secret.key.apiSauceNAO="4ddda08c86e31d0c76681de67994a1eb48ea0ff1" \
    -v /mnt/user/Unraid/Download/Pixiv/downloads:/Pixiv/downloads \
    -v /mnt/user/appdata/Pixiv/usr/.token:/Pixiv/usr/.token \
    registry.cn-hangzhou.aliyuncs.com/zzcabc/pixivbiu:latest

token是從win11電腦客戶端usr獲取的，電腦客戶端能夠正常執行，但是docker無法運行。

錯誤如下：
![317774127-eea9200f-6dd6-4355-9df4-7918df0f223e](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/274500cd-231d-4da0-953e-ab7885c921d2)
出現了網絡問題和token錯誤

想問問怎樣解決？

**Comment by zzcabc** [comment]
> 你好，我也是Unraid docker。我是用這個方式建立 docker run -d --name pixivbiu --user (id−u):(id -g) -p 4001:80 -e sys.debug=false -e sys.apiRoute="direct" -e sys.proxy="no" -e sys.language="zh" -e sys.theme="multiverse" -e sys.autoOpen=true -e sys.ignoreOutdated=false -e biu.search.maxThreads=8 -e biu.search.loadCacheFirst=true -e biu.search.maxCacheSizeMiB=512 -e biu.download.mode="dl-single" -e biu.download.aria2Host="localhost:6800" -e biu.download.aria2Secret="*************" -e biu.download.deterPaths=true -e biu.download.maxDownloading=8 -e biu.download.saveURI="{ROOTPATH}/downloads/{date_today}/" -e biu.download.saveFileName="{title}_{work_id}" -e biu.download.autoArchive=true -e biu.download.whatsUgoira=webp -e biu.download.imageHost="https://i.pximg.net" -e secret.key.apiSauceNAO="**************************" -v /mnt/user/Unraid/Download/Pixiv/downloads:/Pixiv/downloads -v /mnt/user/appdata/Pixiv/usr/.token:/Pixiv/usr/.token registry.cn-hangzhou.aliyuncs.com/zzcabc/pixivbiu:latest
> 
> token是從win11電腦客戶端usr獲取的，電腦客戶端能夠正常執行，但是docker無法運行。
> 
> 錯誤如下： ![317774127-eea9200f-6dd6-4355-9df4-7918df0f223e](https://private-user-images.githubusercontent.com/112755150/317971759-274500cd-231d-4da0-953e-ab7885c921d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTM4NTIsIm5iZiI6MTcxMTY5MzU1MiwicGF0aCI6Ii8xMTI3NTUxNTAvMzE3OTcxNzU5LTI3NDUwMGNkLTIzMWQtNGRhMC05NTNlLWFiNzg4NWM5MjFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwNjI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWZiNTc5YzA5ZmFlM2U0NmI2OWJjMzAyZjVhYzQ0OGZlOGExNWMxOGMwYWY3MDRlM2FiMzdjODUwN2Q5Y2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JsP3MWcDBoBsv6Lj4NJeZCZYB8FDihzVA1ERdY8ZZ1I) 出現了網絡問題和token錯誤
> 
> 想問問怎樣解決？


先修正问题
`-p 4001:80` 代码使用的端口是4001，这里是`-p 可用端口:4001`

取消映射 `/mnt/user/appdata/Pixiv/usr/.token:/Pixiv/usr/.token `
尝试使用`docker attach pixivbiu(容器名称或容器id)` 然后手动从容器内设置token
使用attach命令需要容器启动，先使用`docker start pixivbiu`然后马上输入`docker attach pixivbiu`

**Comment by SA8620** [comment]
![圖片](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/42120f5e-7730-4aaf-83d1-dcb312cf5ed1)
![圖片](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/50a17031-6734-4732-8d20-fd6c61f9c909)
我直接改用應用商店提供的模板

**Comment by zzcabc** [comment]
> 因為我發現打指令和模板提供的都差不多 取消映射 /mnt/user/appdata/Pixiv/usr/.token:/Pixiv/usr/.token 反而沒有出現token錯誤信息,是直接沒有做檢查token這個動作.要依賴容器啟動成功後透過命令介面輸入,像主機客戶端一樣.但就是會自動終止無法進行輸入.也就是無法進入第1步. 這個問題我也有問原作者[txperl](https://github.com/txperl),他叫我可以嘗試執行 PixivBiu Ubuntu 的编译包,但我不想開虛擬機.

是的，可能token只能使用一次，无法进行替换，我已经在拷打他了，看看能不能在输入命令之前能不能等待几秒，以便用户可以进入到docker中

**Comment by SA8620** [comment]
不急不急慢慢來

**Comment by zzcabc** [comment]
> 不急不急慢慢來

如果可以的话，帮我进行测试，只需要将docker image改成 `zzcabc/pixivbiu-test:latest-src`

**Comment by SA8620** [comment]
![圖片](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/c47dbdd7-8a2f-4fb7-8a87-950c62fec5b0)

**Comment by zzcabc** [comment]
@SA8620 我傻逼了，

**Comment by SA8620** [comment]
![註解 2024-04-01 134201](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/5eb50367-38ba-45ba-aefa-de4ca28058ba)
![圖片](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/cd1d336d-3206-4865-8297-3fdf787bd164)
![註解 2024-04-01 134355](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/e1578564-7d24-4d7e-bfda-f40e0a557cdd)
docker run -dit \
    --name pixivbiu \
    -p 4001:4001 \
    -e sys.debug=false \
    -e sys.apiRoute="direct" \
    -e sys.proxy="no" \
    -e sys.language="zh" \
    -e sys.theme="multiverse" \
	-e sys.autoOpen=true \
	-e sys.ignoreOutdated=false \
    -e biu.search.maxThreads=8 \
    -e biu.search.loadCacheFirst=true \
    -e biu.search.maxCacheSizeMiB=512 \
    -e biu.download.mode="dl-single" \
    -e biu.download.aria2Host="localhost:6800" \
    -e biu.download.aria2Secret="xiaodi" \
    -e biu.download.deterPaths=true \
    -e biu.download.maxDownloading=8 \
    -e biu.download.saveURI="{ROOTPATH}/downloads/{date_today}/" \
    -e biu.download.saveFileName="{title}_{work_id}" \
    -e biu.download.autoArchive=true \
    -e biu.download.whatsUgoira=webp \
    -e biu.download.imageHost="https://i.pximg.net" \
    -e secret.key.apiSauceNAO="4ddda08c86e31d0c76681de67994a1eb48ea0ff1" \
    -v /mnt/user/Unraid/Download/Pixiv:/Pixiv/downloads \
    zzcabc/pixivbiu

**Comment by zzcabc** [comment]
这里似乎是你的网络问题，在命令行输入 `curl public-api.secure.pixiv.net` 是否返回403
另外我有点不解，有很多环境变量都是默认的，为什么还要设置
直接使用不行吗
```sh
docker run -dit \
--name pixivbiu \
-p 4001:4001 \
-e secret.key.apiSauceNAO="4ddda08c86e31d0c76681de67994a1eb48ea0ff1" \
-v /mnt/user/Unraid/Download/Pixiv:/Pixiv/downloads \
zzcabc/pixivbiu
```

**Comment by SA8620** [comment]
![圖片](https://github.com/zzcabc/Docker_Buildx_PixivBiu/assets/112755150/7af98f68-0e5a-4cb7-b770-1bcf173ed035)
原本用Aria2 pro下載，Zh語言，下載10，更改檔案命名方式，就全部打掉了。

**Comment by zzcabc** [comment]
第一个异常表明脚本在尝试进行网络登录操作时出错了，具体是因为缺失了 refresh_token，这通常用于刷新过期的登录令牌。
第二个异常与 SSL 连接有关。错误信息 “Cannot create a client socket with a PROTOCOL_TLS_SERVER context” 指出程序试图以 TLS 服务器协议创建一个客户端套接字，这通常是不合适的，因为客户端和服务器使用的是不同的SSL/TLS配置。
第三个异常 “Max retries exceeded with url” 通常发生在 HTTP 请求尝试了多次后仍然失败时。

**Comment by SA8620** [comment]
這個我就不會弄了，想放棄了。謝謝你，打擾了

**Comment by yushizui** [comment]
> 這個我就不會弄了，想放棄了。謝謝你，打擾了

就是网络的问题，环境变量里加上sock5代理就能用，直接挂载了上传的客户端提取的token直接打开就行，格式是socks5://192.168.0.1:1080，加前错误和你的一摸一样，但pc上直接打开程序就能用不知道为啥，我路由器直接开了passwall分流的，怀疑和docker的bridge网关没有ipv6有关
